version: "3"
services:

  web:
    build: .
    ports:
    - "5000:5000"

  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /tmp/zookeeper:/var/lib/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    volumes:
      - /tmp/kafka:/var/lib/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: speaker_diarisation
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
