version: "2"
services:

  web:
    build: .
    volumes:
    - ./src:/src
    ports:
    - 5000:5000
    - 5555:5555

  rabitmq:
    image: rabbitmq:3.7.4
    ports:
      - 5672:5672
      - 5671:5671
      - 25672:25672

  db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: speaker_diarisation
#    volumes:
#      - /tmp/postgres:/var/lib/postgresql/data
